# Generated by Django 3.2 on 2021-09-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymApp', '0005_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='days',
            field=models.CharField(max_length=50),
        ),
    ]
