# Generated by Django 3.2 on 2021-10-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymApp', '0011_auto_20211013_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionist',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
