# Generated by Django 3.2 on 2021-10-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppAdmin', '0002_suplementation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('calorias', models.FloatField()),
            ],
        ),
    ]
