# Generated by Django 3.2 on 2021-10-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymApp', '0010_nutricionist_trainer'),
        ('ProyectoGymAppAdmin', '0003_alimentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymApp.trainer'),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
