# Generated by Django 3.2 on 2021-10-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppAdmin', '0006_alter_entrenamiento_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
