# Generated by Django 3.2 on 2021-10-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppAdmin', '0008_auto_20211013_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule_day',
            name='classSchedule_id',
        ),
        migrations.RemoveField(
            model_name='classschedule_day',
            name='day_id',
        ),
        migrations.RemoveField(
            model_name='clientclass',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='days_of_week',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('K', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='class',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='ClassSchedule_Day',
        ),
        migrations.DeleteModel(
            name='ClientClass',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
