# Generated by Django 3.2 on 2021-10-13 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoGymApp', '0012_auto_20211013_1746'),
        ('ProyectoGymAppAdmin', '0009_auto_20211013_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='hola')),
                ('days_of_week', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('K', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('capacity', models.IntegerField(default=0)),
                ('inscritos', models.IntegerField(default=0)),
                ('clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymApp.trainer')),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
