# Generated by Django 3.2 on 2021-10-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppAdmin', '0011_alter_clase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='clients',
        ),
    ]
