# Generated by Django 3.2 on 2021-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0002_auto_20210929_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='objective',
            field=models.CharField(max_length=50),
        ),
    ]
