# Generated by Django 3.2 on 2021-10-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0003_auto_20210929_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('difficulty', models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1)),
                ('category', models.CharField(choices=[('E', 'Estiramientos'), ('PC', 'Peso corporal'), ('B', 'Barra'), ('M', 'Mancuernas')], max_length=2)),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscles_involved', models.ManyToManyField(to='ProyectoGymAppCliente.Ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='muscles_involved',
            field=models.ManyToManyField(to='ProyectoGymAppCliente.Muscles'),
        ),
    ]
