# Generated by Django 3.2 on 2021-10-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0004_auto_20211002_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscles',
            name='muscles_involved',
        ),
    ]
