# Generated by Django 3.2 on 2021-10-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0005_remove_muscles_muscles_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscles',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
