# Generated by Django 3.2 on 2021-10-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
