# Generated by Django 3.2 on 2021-10-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio_Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('ejercicios', models.ManyToManyField(through='ProyectoGymAppCliente.Ejercicio_Rutina', to='ProyectoGymAppCliente.Ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio_rutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.rutina'),
        ),
    ]
