# Generated by Django 3.2 on 2021-10-20 21:49

import ProyectoGymAppCliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ProyectoGymAppCliente.models.filepath)),
            ],
        ),
    ]
