# Generated by Django 3.2 on 2021-10-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0010_auto_20211015_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='training_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.planentrenamiento'),
        ),
        migrations.AddField(
            model_name='rutina_planentrenamiento',
            name='level',
            field=models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='P    ', max_length=1),
        ),
        migrations.AddField(
            model_name='rutina_planentrenamiento',
            name='objective',
            field=models.CharField(choices=[('H', 'Hipertrofia muscular'), ('QyB', 'Quemar grasa y bajar de peso')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='experience',
            field=models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='objective',
            field=models.CharField(choices=[('H', 'Hipertrofia muscular'), ('QyB', 'Quemar grasa y bajar de peso')], max_length=5),
        ),
    ]
