# Generated by Django 3.2 on 2021-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0011_auto_20211019_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina_planentrenamiento',
            name='level',
            field=models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='P', max_length=1),
        ),
    ]
