# Generated by Django 3.2 on 2021-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0012_alter_rutina_planentrenamiento_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina_planentrenamiento',
            name='level',
        ),
        migrations.RemoveField(
            model_name='rutina_planentrenamiento',
            name='objective',
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='level',
            field=models.CharField(choices=[('P', 'Principiante'), ('I', 'Intermedio'), ('A', 'Avanzado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='objective',
            field=models.CharField(choices=[('H', 'Hipertrofia muscular'), ('QyB', 'Quemar grasa y bajar de peso')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='category',
            field=models.CharField(choices=[('E', 'Estiramientos'), ('PC', 'Peso corporal'), ('B', 'Barra'), ('M', 'Mancuernas'), ('P', 'Polea')], max_length=2),
        ),
    ]
