# Generated by Django 3.2 on 2021-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0013_auto_20211019_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina_planentrenamiento',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rutina_planentrenamiento',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
