# Generated by Django 3.2 on 2021-10-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymApp', '0012_auto_20211013_1746'),
        ('ProyectoGymAppCliente', '0014_auto_20211019_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='phone',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymApp.profile'),
        ),
        migrations.AddField(
            model_name='planentrenamiento',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
