# Generated by Django 3.2 on 2021-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0015_auto_20211020_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='category',
            field=models.CharField(choices=[('E', 'Estiramientos'), ('PC', 'Peso corporal'), ('B', 'Barra'), ('M', 'Mancuernas'), ('P', 'Polea'), ('BE', 'Banda Elástica')], max_length=2),
        ),
    ]
