# Generated by Django 3.2 on 2021-10-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0016_alter_ejercicio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio_rutina',
            name='adicionales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicio_rutina',
            name='fallo',
            field=models.BooleanField(default=False),
        ),
    ]
