# Generated by Django 3.2 on 2021-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0017_auto_20211020_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio_rutina',
            name='adicionales',
        ),
        migrations.AddField(
            model_name='ejercicio_rutina',
            name='rep_adicionales',
            field=models.IntegerField(default=0, verbose_name='Repeticiones Adicionales'),
        ),
    ]
