# Generated by Django 3.2 on 2021-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0018_auto_20211020_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio_rutina',
            name='repeticiones',
            field=models.IntegerField(default=0),
        ),
    ]
