# Generated by Django 3.2 on 2021-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0021_alter_ejercicio_rutina_repeticiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio_rutina',
            name='sets_adicionales',
            field=models.IntegerField(default=0, verbose_name='Sets Adicionales'),
        ),
    ]
