# Generated by Django 3.2 on 2021-10-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0022_ejercicio_rutina_sets_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio_rutina',
            name='repeticiones',
            field=models.IntegerField(default=0, verbose_name='Repeticiones/Pasos'),
        ),
    ]
