# Generated by Django 3.2 on 2021-10-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0023_alter_ejercicio_rutina_repeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
