# Generated by Django 3.2 on 2021-10-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0009_gallery'),
        ('ProyectoGymAppCliente', '0024_auto_20211020_1813'),
    ]

    operations = [
    ]
