# Generated by Django 3.2 on 2021-11-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0025_merge_0009_gallery_0024_auto_20211020_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_comida', models.IntegerField(choices=[(1, 'Comida 1'), (2, 'Comida 2'), (3, 'Comida 3'), (4, 'Comida 4'), (5, 'Comida 5'), (6, 'Comida 6'), (7, 'Comida 7'), (8, 'Comida 8')])),
                ('plan_nutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.planentrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('caloriasXgr', models.IntegerField(null=True)),
                ('ulrPhoto', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMinGr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidadMaxGr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cucharadas', models.IntegerField(max_length=1, null=True)),
                ('unidades', models.IntegerField(max_length=1, null=True)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.comida')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadMinGr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidadMaxGr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cucharadas', models.IntegerField(max_length=1, null=True)),
                ('unidades', models.IntegerField(max_length=1, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.food')),
                ('lista_ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.listaingredientes')),
            ],
        ),
        migrations.AddField(
            model_name='listaingredientes',
            name='food',
            field=models.ManyToManyField(through='ProyectoGymAppCliente.Opciones', to='ProyectoGymAppCliente.Food'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='nutritional_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.plannutricional'),
        ),
    ]
