# Generated by Django 3.2 on 2021-11-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0026_auto_20211118_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaingredientes',
            name='cucharadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listaingredientes',
            name='unidades',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='cucharadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='unidades',
            field=models.IntegerField(null=True),
        ),
    ]
