# Generated by Django 3.2 on 2021-11-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0028_evaluation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='plan_nutricional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.plannutricional'),
        ),
    ]
