# Generated by Django 3.2 on 2021-11-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0030_auto_20211119_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaingredientes',
            name='num_lista',
            field=models.IntegerField(default=1),
        ),
    ]
