# Generated by Django 3.2 on 2021-11-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0031_listaingredientes_num_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
