# Generated by Django 3.2 on 2021-11-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0032_auto_20211122_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannutricional',
            name='objective',
            field=models.CharField(choices=[('H', 'Hipertrofia muscular'), ('QyB', 'Quemar grasa y bajar de peso')], max_length=5, null=True),
        ),
    ]
