# Generated by Django 3.2 on 2021-11-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0033_plannutricional_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('ListaIngredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.listaingredientes')),
            ],
        ),
    ]
