# Generated by Django 3.2 on 2021-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0035_alter_evaluation_nutritional_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientonutricional',
            name='PlanNutricional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.plannutricional'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NutritionalPlanDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('planNutricional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.plannutricional')),
            ],
        ),
    ]
