# Generated by Django 3.2 on 2021-11-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0036_auto_20211123_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaingredientes',
            name='cantidadMaxGr',
        ),
        migrations.RemoveField(
            model_name='listaingredientes',
            name='cantidadMinGr',
        ),
        migrations.RemoveField(
            model_name='listaingredientes',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='listaingredientes',
            name='cucharadas',
        ),
        migrations.RemoveField(
            model_name='listaingredientes',
            name='num_lista',
        ),
        migrations.RemoveField(
            model_name='listaingredientes',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='cantidadMaxGr',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='cantidadMinGr',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='cucharadas',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='seguimientonutricional',
            name='ListaIngredientes',
        ),
        migrations.AddField(
            model_name='comida',
            name='lista_ingredientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.listaingredientes'),
        ),
        migrations.AddField(
            model_name='comida',
            name='num_lista',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listaingredientes',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listaingredientes',
            name='plan_nutricional',
            field=models.ManyToManyField(through='ProyectoGymAppCliente.Comida', to='ProyectoGymAppCliente.PlanNutricional'),
        ),
        migrations.AddField(
            model_name='seguimientonutricional',
            name='comida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoGymAppCliente.comida'),
        ),
    ]
