# Generated by Django 3.2 on 2021-11-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGymAppCliente', '0039_alter_listaingredientes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientonutricional',
            name='day',
        ),
        migrations.RemoveField(
            model_name='seguimientonutricional',
            name='month',
        ),
    ]
